/**
 * End-to-end email pipeline test.
 *
 * Tests that audit-complete emails send correctly for both finalization paths:
 *   1. Perfect score (100%) — all questions answered Yes
 *   2. Invalid Genie     — no recording found, score 0
 *
 * Hits the live /webhooks/audit-complete endpoint with mock finding payloads.
 * Bypasses webhook config recipients via ?testOverrideTo= so this test works
 * regardless of what testEmail is set in the admin dashboard.
 *
 * Usage:
 *   deno run --allow-net --allow-env --allow-read --env test/email-pipeline.ts <orgId> [selfUrl]
 *
 * Examples:
 *   deno run --allow-net --allow-env --allow-read --env test/email-pipeline.ts mrg
 *   deno run --allow-net --allow-env --allow-read --env test/email-pipeline.ts mrg https://autobottom.deno.dev
 */

const TEST_RECIPIENTS = "adamp@monsterrg.com,ai@monsterrg.com,alexandera@monsterrg.com";

const orgId = Deno.args[0];
if (!orgId) {
  console.error("❌ Usage: deno run ... test/email-pipeline.ts <orgId> [selfUrl]");
  Deno.exit(1);
}

const selfUrl = (Deno.args[1] || Deno.env.get("SELF_URL") || "").replace(/\/$/, "");
if (!selfUrl) {
  console.error("❌ selfUrl required — pass as 2nd arg or set SELF_URL in .env");
  Deno.exit(1);
}

// ---------------------------------------------------------------------------
// Mock finding base — shared fields
// ---------------------------------------------------------------------------
const BASE_FINDING = {
  recordingIdField: "DateLegId",
  recordingId: "TEST-RECORDING-99",
  owner: "ai@monsterrg.com",
  record: {
    RecordId: "99999",
    VoName: "VO MB - Test Agent",
    VoEmail: "ai@monsterrg.com",
    SupervisorEmail: "",
    GmEmail: "",
    GuestName: "John Testguest",
    ActivatingOffice: "Test Office",
  },
  feedback: {
    text: "This is test feedback generated by the email pipeline test.",
  },
};

// ---------------------------------------------------------------------------
// Scenario 1: Perfect score — all Yes, reason: perfect_score
// ---------------------------------------------------------------------------
const PERFECT_SCORE_FINDING = {
  ...BASE_FINDING,
  id: "TEST-PERFECT-SCORE-001",
  findingStatus: "finished",
  answeredQuestions: [
    { question: "Did the agent verify the guest's identity?", header: "Identity Verification", answer: "Yes", thinking: "Agent confirmed name and booking.", defense: "N/A" },
    { question: "Did the agent offer available amenities?", header: "Amenities Offer", answer: "Yes", thinking: "Agent listed all relevant amenities.", defense: "N/A" },
    { question: "Did the agent follow the required script?", header: "Script Adherence", answer: "Yes", thinking: "Script was followed throughout.", defense: "N/A" },
    { question: "Did the agent resolve the guest's issue?", header: "Issue Resolution", answer: "Yes", thinking: "Issue was fully resolved.", defense: "N/A" },
  ],
};

// ---------------------------------------------------------------------------
// Scenario 2: Invalid Genie — recording not found, all No, reason: invalid_genie
// ---------------------------------------------------------------------------
const INVALID_GENIE_FINDING = {
  ...BASE_FINDING,
  id: "TEST-INVALID-GENIE-001",
  findingStatus: "no recording",
  rawTranscript: "Invalid Genie — recording could not be located for this ID.",
  answeredQuestions: [
    { question: "Did the agent verify the guest's identity?", header: "Identity Verification", answer: "No", thinking: "No recording available.", defense: "N/A - No Audio" },
    { question: "Did the agent offer available amenities?", header: "Amenities Offer", answer: "No", thinking: "No recording available.", defense: "N/A - No Audio" },
    { question: "Did the agent follow the required script?", header: "Script Adherence", answer: "No", thinking: "No recording available.", defense: "N/A - No Audio" },
    { question: "Did the agent resolve the guest's issue?", header: "Issue Resolution", answer: "No", thinking: "No recording available.", defense: "N/A - No Audio" },
  ],
};

// ---------------------------------------------------------------------------
// Test runner
// ---------------------------------------------------------------------------
async function testScenario(opts: {
  label: string;
  finding: Record<string, unknown>;
  score: number;
  reason: string;
}) {
  const { label, finding, score, reason } = opts;
  console.log(`\n🔍 ${label}`);
  console.log(`   finding.id = ${finding.id}  score = ${score}%  reason = ${reason}`);

  const endpoint =
    `${selfUrl}/webhooks/audit-complete` +
    `?org=${encodeURIComponent(orgId)}` +
    `&testOverrideTo=${encodeURIComponent(TEST_RECIPIENTS)}`;

  let res: Response;
  try {
    res = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        finding,
        score,
        reason,
        terminatedAt: new Date().toISOString(),
      }),
    });
  } catch (err) {
    console.error(`   ❌ Network error: ${err}`);
    return;
  }

  let data: Record<string, unknown> = {};
  try { data = await res.json(); } catch { /* ignore */ }

  if (!res.ok || data.error) {
    console.error(`   ❌ HTTP ${res.status}: ${JSON.stringify(data)}`);
    return;
  }

  if (data.skipped) {
    console.warn(`   ⚠️  Skipped — ${data.skipped}`);
    console.warn(`      → Make sure an email template is configured in the admin dashboard`);
    console.warn(`        (Admin → Email Templates) and assigned in the terminate webhook config.`);
    return;
  }

  console.log(`   ✅ Sent → ${data.to}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
console.log("🚀 Email pipeline test");
console.log(`   org      : ${orgId}`);
console.log(`   service  : ${selfUrl}`);
console.log(`   recipients: ${TEST_RECIPIENTS}`);

await testScenario({
  label: "Scenario 1 — Perfect Score (100%)",
  finding: PERFECT_SCORE_FINDING,
  score: 100,
  reason: "perfect_score",
});

await testScenario({
  label: "Scenario 2 — Invalid Genie (no recording)",
  finding: INVALID_GENIE_FINDING,
  score: 0,
  reason: "invalid_genie",
});

// ---------------------------------------------------------------------------
// Optional: trigger a real audit re-run by RecordId (pass as 3rd arg)
// Example: deno task test:email <orgId> <selfUrl> 453454
// ---------------------------------------------------------------------------
const rerunRid = Deno.args[2];
if (rerunRid) {
  console.log(`\n🔄 Triggering live re-audit for RecordId ${rerunRid}...`);
  try {
    const rerunUrl = `${selfUrl}/audit/test-by-rid?rid=${encodeURIComponent(rerunRid)}&org=${encodeURIComponent(orgId)}`;
    const res = await fetch(rerunUrl, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" });
    const data = await res.json().catch(() => ({}));
    if (res.ok) {
      console.log(`   ✅ Re-audit enqueued — findingId=${data.findingId ?? "?"} jobId=${data.jobId ?? "?"}`);
      console.log(`   → Watch Deno Deploy logs for [STEP-FINALIZE] and [WEBHOOK:terminate] entries`);
    } else {
      console.error(`   ❌ Re-audit failed — HTTP ${res.status}: ${JSON.stringify(data)}`);
    }
  } catch (err) {
    console.error(`   ❌ Re-audit network error: ${err}`);
  }
}

console.log(`\n✅ Done. Check inboxes: ${TEST_RECIPIENTS}`);
