// WARNING: DO NOT EDIT THIS FILE. It is autogenerated by Fresh.
import { setBuildCache, ProdBuildCache, path } from "fresh/internal";
import * as snapshot from "./snapshot.js";
import { app } from "../main.ts";

const root = path.join(import.meta.dirname, "..");
setBuildCache(app, new ProdBuildCache(root, snapshot), "production");

export default {
  fetch: app.handler()
};
