// WARNING: DO NOT EDIT THIS FILE. It is autogenerated by Fresh.
import { IslandPreparer } from "fresh/internal";
import * as SoundEngine from "../islands/SoundEngine.tsx";
import * as HotkeyHandler from "../islands/HotkeyHandler.tsx";
import * as ChatInput from "../islands/ChatInput.tsx";
import * as fsRoute_0 from "../routes/_app.tsx"
import * as fsRoute_1 from "../routes/_middleware.ts"
import * as fsRoute_2 from "../routes/_500.tsx"
import * as fsRoute_3 from "../routes/_404.tsx"

export const clientEntry = "/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/fresh-runtime.js"
export const version = "73dd940f22b24978269c29d418718a0057cb37bc"

export const islands = new Map();
const islandPreparer = new IslandPreparer();
islandPreparer.prepare(islands, SoundEngine, "/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/SoundEngine.js", "SoundEngine", []);
islandPreparer.prepare(islands, HotkeyHandler, "/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/HotkeyHandler.js", "HotkeyHandler", []);
islandPreparer.prepare(islands, ChatInput, "/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/ChatInput.js", "ChatInput", []);

export const staticFiles = new Map([
  ["/favicon.svg", {"name":"/favicon.svg","hash":"66c0ae4b1956c0e76e490ca3f79bfd02bd385ff24c35908f25ef49e6bd286989","filePath":"static/favicon.svg","contentType":"image/svg+xml"}],
  ["/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/fresh-runtime.js", {"name":"/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/fresh-runtime.js","hash":"erqGD4HuIqQ","filePath":"_fresh/static/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/fresh-runtime.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/SoundEngine.js", {"name":"/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/SoundEngine.js","hash":"UPcnj8xwq8s","filePath":"_fresh/static/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/SoundEngine.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/HotkeyHandler.js", {"name":"/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/HotkeyHandler.js","hash":"lBON637qbSc","filePath":"_fresh/static/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/HotkeyHandler.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/ChatInput.js", {"name":"/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/ChatInput.js","hash":"3oOqlxUWt5Q","filePath":"_fresh/static/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/ChatInput.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/chunk-EAQD6YFO.js", {"name":"/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/chunk-EAQD6YFO.js","hash":"0ncFaEW88EI","filePath":"_fresh/static/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/chunk-EAQD6YFO.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/chunk-HGON2IZK.js", {"name":"/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/chunk-HGON2IZK.js","hash":"9dWO//DQy+8","filePath":"_fresh/static/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/chunk-HGON2IZK.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/metafile.json", {"name":"/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/metafile.json","hash":"43455f2fa75f50cf89298787961ed1244c25b2f36cbd204cef904c7e1b249de8","filePath":"_fresh/static/_fresh/js/73dd940f22b24978269c29d418718a0057cb37bc/metafile.json","contentType":"application/json; charset=UTF-8"}],
  ["/styles.css", {"name":"/styles.css","hash":"f989d02970308d03fd9f61f8fca331a073c5dc017b489f119f60f217413dfadd","filePath":"_fresh/static/styles.css","contentType":"text/css; charset=UTF-8"}]
]);

export const entryAssets = [];

export const fsRoutes = [
  { id: "/_app", mod: fsRoute_0, type: "app", pattern: "*", routePattern: "*" },
  { id: "/_middleware", mod: fsRoute_1, type: "middleware", pattern: "/", routePattern: "/" },
  { id: "/_500", mod: fsRoute_2, type: "error", pattern: "/", routePattern: "/" },
  { id: "/_404", mod: fsRoute_3, type: "notFound", pattern: "*", routePattern: "*" },
  { id: "/index", mod: () => import("../routes/index.tsx"), type: "route", pattern: "/", routePattern: "/" },
  { id: "/login", mod: () => import("../routes/login.tsx"), type: "route", pattern: "/login", routePattern: "/login" },
  { id: "/chat/index", mod: () => import("../routes/chat/index.tsx"), type: "route", pattern: "/chat/", routePattern: "/chat" },
  { id: "/admin/weekly-builder", mod: () => import("../routes/admin/weekly-builder.tsx"), type: "route", pattern: "/admin/weekly-builder", routePattern: "/admin/weekly-builder" },
  { id: "/admin/audits", mod: () => import("../routes/admin/audits.tsx"), type: "route", pattern: "/admin/audits", routePattern: "/admin/audits" },
  { id: "/admin/dashboard", mod: () => import("../routes/admin/dashboard.tsx"), type: "route", pattern: "/admin/dashboard", routePattern: "/admin/dashboard" },
  { id: "/admin/users", mod: () => import("../routes/admin/users.tsx"), type: "route", pattern: "/admin/users", routePattern: "/admin/users" },
  { id: "/register", mod: () => import("../routes/register.tsx"), type: "route", pattern: "/register", routePattern: "/register" },
  { id: "/agent/index", mod: () => import("../routes/agent/index.tsx"), type: "route", pattern: "/agent/", routePattern: "/agent" },
  { id: "/manager/index", mod: () => import("../routes/manager/index.tsx"), type: "route", pattern: "/manager/", routePattern: "/manager" },
  { id: "/review/index", mod: () => import("../routes/review/index.tsx"), type: "route", pattern: "/review/", routePattern: "/review" },
  { id: "/review/dashboard", mod: () => import("../routes/review/dashboard.tsx"), type: "route", pattern: "/review/dashboard", routePattern: "/review/dashboard" },
  { id: "/judge/index", mod: () => import("../routes/judge/index.tsx"), type: "route", pattern: "/judge/", routePattern: "/judge" },
  { id: "/judge/dashboard", mod: () => import("../routes/judge/dashboard.tsx"), type: "route", pattern: "/judge/dashboard", routePattern: "/judge/dashboard" },
  { id: "/api/login", mod: () => import("../routes/api/login.ts"), type: "route", pattern: "/api/login", routePattern: "/api/login" },
  { id: "/api/chat/send", mod: () => import("../routes/api/chat/send.ts"), type: "route", pattern: "/api/chat/send", routePattern: "/api/chat/send" },
  { id: "/api/chat/thread", mod: () => import("../routes/api/chat/thread.tsx"), type: "route", pattern: "/api/chat/thread", routePattern: "/api/chat/thread" },
  { id: "/api/admin/users-delete", mod: () => import("../routes/api/admin/users-delete.ts"), type: "route", pattern: "/api/admin/users-delete", routePattern: "/api/admin/users-delete" },
  { id: "/api/admin/retry", mod: () => import("../routes/api/admin/retry.ts"), type: "route", pattern: "/api/admin/retry", routePattern: "/api/admin/retry" },
  { id: "/api/admin/stats", mod: () => import("../routes/api/admin/stats.tsx"), type: "route", pattern: "/api/admin/stats", routePattern: "/api/admin/stats" },
  { id: "/api/admin/users", mod: () => import("../routes/api/admin/users.ts"), type: "route", pattern: "/api/admin/users", routePattern: "/api/admin/users" },
  { id: "/api/admin/queue-action", mod: () => import("../routes/api/admin/queue-action.ts"), type: "route", pattern: "/api/admin/queue-action", routePattern: "/api/admin/queue-action" },
  { id: "/api/manager/remediate", mod: () => import("../routes/api/manager/remediate.ts"), type: "route", pattern: "/api/manager/remediate", routePattern: "/api/manager/remediate" },
  { id: "/api/manager/add-agent", mod: () => import("../routes/api/manager/add-agent.ts"), type: "route", pattern: "/api/manager/add-agent", routePattern: "/api/manager/add-agent" },
  { id: "/api/manager/delete-agent", mod: () => import("../routes/api/manager/delete-agent.ts"), type: "route", pattern: "/api/manager/delete-agent", routePattern: "/api/manager/delete-agent" },
  { id: "/api/review/decide", mod: () => import("../routes/api/review/decide.tsx"), type: "route", pattern: "/api/review/decide", routePattern: "/api/review/decide" },
  { id: "/api/review/back", mod: () => import("../routes/api/review/back.tsx"), type: "route", pattern: "/api/review/back", routePattern: "/api/review/back" },
  { id: "/api/judge/decide", mod: () => import("../routes/api/judge/decide.tsx"), type: "route", pattern: "/api/judge/decide", routePattern: "/api/judge/decide" },
  { id: "/api/judge/back", mod: () => import("../routes/api/judge/back.tsx"), type: "route", pattern: "/api/judge/back", routePattern: "/api/judge/back" },
  { id: "/api/register", mod: () => import("../routes/api/register.ts"), type: "route", pattern: "/api/register", routePattern: "/api/register" },
  { id: "/api/logout", mod: () => import("../routes/api/logout.ts"), type: "route", pattern: "/api/logout", routePattern: "/api/logout" },
  { id: "/api/store/buy", mod: () => import("../routes/api/store/buy.ts"), type: "route", pattern: "/api/store/buy", routePattern: "/api/store/buy" },
  { id: "/question-lab/index", mod: () => import("../routes/question-lab/index.tsx"), type: "route", pattern: "/question-lab/", routePattern: "/question-lab" },
  { id: "/store/index", mod: () => import("../routes/store/index.tsx"), type: "route", pattern: "/store/", routePattern: "/store" },
];
