// WARNING: DO NOT EDIT THIS FILE. It is autogenerated by Fresh.
import { IslandPreparer } from "fresh/internal";
import * as ModalController from "../islands/ModalController.tsx";
import * as SoundEngine from "../islands/SoundEngine.tsx";
import * as HotkeyHandler from "../islands/HotkeyHandler.tsx";
import * as ChatInput from "../islands/ChatInput.tsx";
import * as fsRoute_0 from "../routes/_app.tsx"
import * as fsRoute_1 from "../routes/_middleware.ts"
import * as fsRoute_2 from "../routes/_500.tsx"
import * as fsRoute_3 from "../routes/_404.tsx"

export const clientEntry = "/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/fresh-runtime.js"
export const version = "89e475fbd1685800f6f8478c2e305137fd37c032"

export const islands = new Map();
const islandPreparer = new IslandPreparer();
islandPreparer.prepare(islands, ModalController, "/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/ModalController.js", "ModalController", []);
islandPreparer.prepare(islands, SoundEngine, "/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/SoundEngine.js", "SoundEngine", []);
islandPreparer.prepare(islands, HotkeyHandler, "/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/HotkeyHandler.js", "HotkeyHandler", []);
islandPreparer.prepare(islands, ChatInput, "/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/ChatInput.js", "ChatInput", []);

export const staticFiles = new Map([
  ["/favicon.svg", {"name":"/favicon.svg","hash":"66c0ae4b1956c0e76e490ca3f79bfd02bd385ff24c35908f25ef49e6bd286989","filePath":"static/favicon.svg","contentType":"image/svg+xml"}],
  ["/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/fresh-runtime.js", {"name":"/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/fresh-runtime.js","hash":"ytQlMPjEtHo","filePath":"_fresh/static/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/fresh-runtime.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/ModalController.js", {"name":"/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/ModalController.js","hash":"5rTZ+7MLj5w","filePath":"_fresh/static/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/ModalController.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/SoundEngine.js", {"name":"/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/SoundEngine.js","hash":"UPcnj8xwq8s","filePath":"_fresh/static/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/SoundEngine.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/HotkeyHandler.js", {"name":"/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/HotkeyHandler.js","hash":"lBON637qbSc","filePath":"_fresh/static/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/HotkeyHandler.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/ChatInput.js", {"name":"/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/ChatInput.js","hash":"3oOqlxUWt5Q","filePath":"_fresh/static/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/ChatInput.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/chunk-EAQD6YFO.js", {"name":"/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/chunk-EAQD6YFO.js","hash":"0ncFaEW88EI","filePath":"_fresh/static/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/chunk-EAQD6YFO.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/chunk-HGON2IZK.js", {"name":"/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/chunk-HGON2IZK.js","hash":"9dWO//DQy+8","filePath":"_fresh/static/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/chunk-HGON2IZK.js","contentType":"text/javascript; charset=UTF-8"}],
  ["/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/metafile.json", {"name":"/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/metafile.json","hash":"7cd1f9f83efccf15f3c2ff3d45ce97063ac060aaf231d73f8ee8ad0e2b75c9b9","filePath":"_fresh/static/_fresh/js/89e475fbd1685800f6f8478c2e305137fd37c032/metafile.json","contentType":"application/json; charset=UTF-8"}],
  ["/styles.css", {"name":"/styles.css","hash":"884eaa4da0746b1436ca486097f46f20d9e3817617badf41ef8e462b7b3662f8","filePath":"_fresh/static/styles.css","contentType":"text/css; charset=UTF-8"}]
]);

export const entryAssets = [];

export const fsRoutes = [
  { id: "/_app", mod: fsRoute_0, type: "app", pattern: "*", routePattern: "*" },
  { id: "/_middleware", mod: fsRoute_1, type: "middleware", pattern: "/", routePattern: "/" },
  { id: "/_500", mod: fsRoute_2, type: "error", pattern: "/", routePattern: "/" },
  { id: "/_404", mod: fsRoute_3, type: "notFound", pattern: "*", routePattern: "*" },
  { id: "/index", mod: () => import("../routes/index.tsx"), type: "route", pattern: "/", routePattern: "/" },
  { id: "/login", mod: () => import("../routes/login.tsx"), type: "route", pattern: "/login", routePattern: "/login" },
  { id: "/chat/index", mod: () => import("../routes/chat/index.tsx"), type: "route", pattern: "/chat/", routePattern: "/chat" },
  { id: "/admin/weekly-builder", mod: () => import("../routes/admin/weekly-builder.tsx"), type: "route", pattern: "/admin/weekly-builder", routePattern: "/admin/weekly-builder" },
  { id: "/admin/audits", mod: () => import("../routes/admin/audits.tsx"), type: "route", pattern: "/admin/audits", routePattern: "/admin/audits" },
  { id: "/admin/dashboard", mod: () => import("../routes/admin/dashboard.tsx"), type: "route", pattern: "/admin/dashboard", routePattern: "/admin/dashboard" },
  { id: "/admin/users", mod: () => import("../routes/admin/users.tsx"), type: "route", pattern: "/admin/users", routePattern: "/admin/users" },
  { id: "/register", mod: () => import("../routes/register.tsx"), type: "route", pattern: "/register", routePattern: "/register" },
  { id: "/agent/index", mod: () => import("../routes/agent/index.tsx"), type: "route", pattern: "/agent/", routePattern: "/agent" },
  { id: "/manager/index", mod: () => import("../routes/manager/index.tsx"), type: "route", pattern: "/manager/", routePattern: "/manager" },
  { id: "/review/index", mod: () => import("../routes/review/index.tsx"), type: "route", pattern: "/review/", routePattern: "/review" },
  { id: "/review/dashboard", mod: () => import("../routes/review/dashboard.tsx"), type: "route", pattern: "/review/dashboard", routePattern: "/review/dashboard" },
  { id: "/judge/index", mod: () => import("../routes/judge/index.tsx"), type: "route", pattern: "/judge/", routePattern: "/judge" },
  { id: "/judge/dashboard", mod: () => import("../routes/judge/dashboard.tsx"), type: "route", pattern: "/judge/dashboard", routePattern: "/judge/dashboard" },
  { id: "/api/login", mod: () => import("../routes/api/login.ts"), type: "route", pattern: "/api/login", routePattern: "/api/login" },
  { id: "/api/chat/send", mod: () => import("../routes/api/chat/send.ts"), type: "route", pattern: "/api/chat/send", routePattern: "/api/chat/send" },
  { id: "/api/chat/thread", mod: () => import("../routes/api/chat/thread.tsx"), type: "route", pattern: "/api/chat/thread", routePattern: "/api/chat/thread" },
  { id: "/api/admin/config-save", mod: () => import("../routes/api/admin/config-save.ts"), type: "route", pattern: "/api/admin/config-save", routePattern: "/api/admin/config-save" },
  { id: "/api/admin/users-delete", mod: () => import("../routes/api/admin/users-delete.ts"), type: "route", pattern: "/api/admin/users-delete", routePattern: "/api/admin/users-delete" },
  { id: "/api/admin/webhook-save", mod: () => import("../routes/api/admin/webhook-save.ts"), type: "route", pattern: "/api/admin/webhook-save", routePattern: "/api/admin/webhook-save" },
  { id: "/api/admin/retry", mod: () => import("../routes/api/admin/retry.ts"), type: "route", pattern: "/api/admin/retry", routePattern: "/api/admin/retry" },
  { id: "/api/admin/stats", mod: () => import("../routes/api/admin/stats.tsx"), type: "route", pattern: "/api/admin/stats", routePattern: "/api/admin/stats" },
  { id: "/api/admin/users", mod: () => import("../routes/api/admin/users.ts"), type: "route", pattern: "/api/admin/users", routePattern: "/api/admin/users" },
  { id: "/api/admin/test-audit", mod: () => import("../routes/api/admin/test-audit.ts"), type: "route", pattern: "/api/admin/test-audit", routePattern: "/api/admin/test-audit" },
  { id: "/api/admin/modal/webhook/save", mod: () => import("../routes/api/admin/modal/webhook/save.tsx"), type: "route", pattern: "/api/admin/modal/webhook/save", routePattern: "/api/admin/modal/webhook/save" },
  { id: "/api/admin/modal/pipeline/queues", mod: () => import("../routes/api/admin/modal/pipeline/queues.tsx"), type: "route", pattern: "/api/admin/modal/pipeline/queues", routePattern: "/api/admin/modal/pipeline/queues" },
  { id: "/api/admin/modal/pipeline/save", mod: () => import("../routes/api/admin/modal/pipeline/save.tsx"), type: "route", pattern: "/api/admin/modal/pipeline/save", routePattern: "/api/admin/modal/pipeline/save" },
  { id: "/api/admin/modal/offices", mod: () => import("../routes/api/admin/modal/offices.tsx"), type: "route", pattern: "/api/admin/modal/offices", routePattern: "/api/admin/modal/offices" },
  { id: "/api/admin/modal/maintenance", mod: () => import("../routes/api/admin/modal/maintenance.tsx"), type: "route", pattern: "/api/admin/modal/maintenance", routePattern: "/api/admin/modal/maintenance" },
  { id: "/api/admin/modal/bad-words", mod: () => import("../routes/api/admin/modal/bad-words.tsx"), type: "route", pattern: "/api/admin/modal/bad-words", routePattern: "/api/admin/modal/bad-words" },
  { id: "/api/admin/modal/email-templates/delete", mod: () => import("../routes/api/admin/modal/email-templates/delete.tsx"), type: "route", pattern: "/api/admin/modal/email-templates/delete", routePattern: "/api/admin/modal/email-templates/delete" },
  { id: "/api/admin/modal/email-templates/save", mod: () => import("../routes/api/admin/modal/email-templates/save.tsx"), type: "route", pattern: "/api/admin/modal/email-templates/save", routePattern: "/api/admin/modal/email-templates/save" },
  { id: "/api/admin/modal/email-reports/send-now", mod: () => import("../routes/api/admin/modal/email-reports/send-now.tsx"), type: "route", pattern: "/api/admin/modal/email-reports/send-now", routePattern: "/api/admin/modal/email-reports/send-now" },
  { id: "/api/admin/modal/email-reports/delete", mod: () => import("../routes/api/admin/modal/email-reports/delete.tsx"), type: "route", pattern: "/api/admin/modal/email-reports/delete", routePattern: "/api/admin/modal/email-reports/delete" },
  { id: "/api/admin/modal/email-reports/save", mod: () => import("../routes/api/admin/modal/email-reports/save.tsx"), type: "route", pattern: "/api/admin/modal/email-reports/save", routePattern: "/api/admin/modal/email-reports/save" },
  { id: "/api/admin/modal/bad-words/add-word", mod: () => import("../routes/api/admin/modal/bad-words/add-word.tsx"), type: "route", pattern: "/api/admin/modal/bad-words/add-word", routePattern: "/api/admin/modal/bad-words/add-word" },
  { id: "/api/admin/modal/bad-words/toggle-all-offices", mod: () => import("../routes/api/admin/modal/bad-words/toggle-all-offices.tsx"), type: "route", pattern: "/api/admin/modal/bad-words/toggle-all-offices", routePattern: "/api/admin/modal/bad-words/toggle-all-offices" },
  { id: "/api/admin/modal/bad-words/remove-office", mod: () => import("../routes/api/admin/modal/bad-words/remove-office.tsx"), type: "route", pattern: "/api/admin/modal/bad-words/remove-office", routePattern: "/api/admin/modal/bad-words/remove-office" },
  { id: "/api/admin/modal/bad-words/remove-word", mod: () => import("../routes/api/admin/modal/bad-words/remove-word.tsx"), type: "route", pattern: "/api/admin/modal/bad-words/remove-word", routePattern: "/api/admin/modal/bad-words/remove-word" },
  { id: "/api/admin/modal/bad-words/add-office", mod: () => import("../routes/api/admin/modal/bad-words/add-office.tsx"), type: "route", pattern: "/api/admin/modal/bad-words/add-office", routePattern: "/api/admin/modal/bad-words/add-office" },
  { id: "/api/admin/modal/bad-words/remove-email", mod: () => import("../routes/api/admin/modal/bad-words/remove-email.tsx"), type: "route", pattern: "/api/admin/modal/bad-words/remove-email", routePattern: "/api/admin/modal/bad-words/remove-email" },
  { id: "/api/admin/modal/bad-words/toggle-enabled", mod: () => import("../routes/api/admin/modal/bad-words/toggle-enabled.tsx"), type: "route", pattern: "/api/admin/modal/bad-words/toggle-enabled", routePattern: "/api/admin/modal/bad-words/toggle-enabled" },
  { id: "/api/admin/modal/bad-words/add-email", mod: () => import("../routes/api/admin/modal/bad-words/add-email.tsx"), type: "route", pattern: "/api/admin/modal/bad-words/add-email", routePattern: "/api/admin/modal/bad-words/add-email" },
  { id: "/api/admin/modal/bonus-points", mod: () => import("../routes/api/admin/modal/bonus-points.tsx"), type: "route", pattern: "/api/admin/modal/bonus-points", routePattern: "/api/admin/modal/bonus-points" },
  { id: "/api/admin/modal/email-templates", mod: () => import("../routes/api/admin/modal/email-templates.tsx"), type: "route", pattern: "/api/admin/modal/email-templates", routePattern: "/api/admin/modal/email-templates" },
  { id: "/api/admin/modal/pipeline", mod: () => import("../routes/api/admin/modal/pipeline.tsx"), type: "route", pattern: "/api/admin/modal/pipeline", routePattern: "/api/admin/modal/pipeline" },
  { id: "/api/admin/modal/impersonate", mod: () => import("../routes/api/admin/modal/impersonate.tsx"), type: "route", pattern: "/api/admin/modal/impersonate", routePattern: "/api/admin/modal/impersonate" },
  { id: "/api/admin/modal/users", mod: () => import("../routes/api/admin/modal/users.tsx"), type: "route", pattern: "/api/admin/modal/users", routePattern: "/api/admin/modal/users" },
  { id: "/api/admin/modal/offices/add-bypass", mod: () => import("../routes/api/admin/modal/offices/add-bypass.tsx"), type: "route", pattern: "/api/admin/modal/offices/add-bypass", routePattern: "/api/admin/modal/offices/add-bypass" },
  { id: "/api/admin/modal/offices/remove-bypass", mod: () => import("../routes/api/admin/modal/offices/remove-bypass.tsx"), type: "route", pattern: "/api/admin/modal/offices/remove-bypass", routePattern: "/api/admin/modal/offices/remove-bypass" },
  { id: "/api/admin/modal/offices/remove-dept", mod: () => import("../routes/api/admin/modal/offices/remove-dept.tsx"), type: "route", pattern: "/api/admin/modal/offices/remove-dept", routePattern: "/api/admin/modal/offices/remove-dept" },
  { id: "/api/admin/modal/offices/add-dept", mod: () => import("../routes/api/admin/modal/offices/add-dept.tsx"), type: "route", pattern: "/api/admin/modal/offices/add-dept", routePattern: "/api/admin/modal/offices/add-dept" },
  { id: "/api/admin/modal/users/create", mod: () => import("../routes/api/admin/modal/users/create.tsx"), type: "route", pattern: "/api/admin/modal/users/create", routePattern: "/api/admin/modal/users/create" },
  { id: "/api/admin/modal/users/scopes", mod: () => import("../routes/api/admin/modal/users/scopes.tsx"), type: "route", pattern: "/api/admin/modal/users/scopes", routePattern: "/api/admin/modal/users/scopes" },
  { id: "/api/admin/modal/users/delete", mod: () => import("../routes/api/admin/modal/users/delete.tsx"), type: "route", pattern: "/api/admin/modal/users/delete", routePattern: "/api/admin/modal/users/delete" },
  { id: "/api/admin/modal/webhook", mod: () => import("../routes/api/admin/modal/webhook.tsx"), type: "route", pattern: "/api/admin/modal/webhook", routePattern: "/api/admin/modal/webhook" },
  { id: "/api/admin/modal/email-reports", mod: () => import("../routes/api/admin/modal/email-reports.tsx"), type: "route", pattern: "/api/admin/modal/email-reports", routePattern: "/api/admin/modal/email-reports" },
  { id: "/api/admin/modal/chargebacks/data", mod: () => import("../routes/api/admin/modal/chargebacks/data.tsx"), type: "route", pattern: "/api/admin/modal/chargebacks/data", routePattern: "/api/admin/modal/chargebacks/data" },
  { id: "/api/admin/modal/chargebacks", mod: () => import("../routes/api/admin/modal/chargebacks.tsx"), type: "route", pattern: "/api/admin/modal/chargebacks", routePattern: "/api/admin/modal/chargebacks" },
  { id: "/api/admin/review-drill", mod: () => import("../routes/api/admin/review-drill.tsx"), type: "route", pattern: "/api/admin/review-drill", routePattern: "/api/admin/review-drill" },
  { id: "/api/admin/queue-action", mod: () => import("../routes/api/admin/queue-action.ts"), type: "route", pattern: "/api/admin/queue-action", routePattern: "/api/admin/queue-action" },
  { id: "/api/admin/find-audit", mod: () => import("../routes/api/admin/find-audit.ts"), type: "route", pattern: "/api/admin/find-audit", routePattern: "/api/admin/find-audit" },
  { id: "/api/manager/remediate", mod: () => import("../routes/api/manager/remediate.ts"), type: "route", pattern: "/api/manager/remediate", routePattern: "/api/manager/remediate" },
  { id: "/api/manager/add-agent", mod: () => import("../routes/api/manager/add-agent.ts"), type: "route", pattern: "/api/manager/add-agent", routePattern: "/api/manager/add-agent" },
  { id: "/api/manager/delete-agent", mod: () => import("../routes/api/manager/delete-agent.ts"), type: "route", pattern: "/api/manager/delete-agent", routePattern: "/api/manager/delete-agent" },
  { id: "/api/review/decide", mod: () => import("../routes/api/review/decide.tsx"), type: "route", pattern: "/api/review/decide", routePattern: "/api/review/decide" },
  { id: "/api/review/back", mod: () => import("../routes/api/review/back.tsx"), type: "route", pattern: "/api/review/back", routePattern: "/api/review/back" },
  { id: "/api/judge/decide", mod: () => import("../routes/api/judge/decide.tsx"), type: "route", pattern: "/api/judge/decide", routePattern: "/api/judge/decide" },
  { id: "/api/judge/back", mod: () => import("../routes/api/judge/back.tsx"), type: "route", pattern: "/api/judge/back", routePattern: "/api/judge/back" },
  { id: "/api/register", mod: () => import("../routes/api/register.ts"), type: "route", pattern: "/api/register", routePattern: "/api/register" },
  { id: "/api/logout", mod: () => import("../routes/api/logout.ts"), type: "route", pattern: "/api/logout", routePattern: "/api/logout" },
  { id: "/api/store/buy", mod: () => import("../routes/api/store/buy.ts"), type: "route", pattern: "/api/store/buy", routePattern: "/api/store/buy" },
  { id: "/question-lab/index", mod: () => import("../routes/question-lab/index.tsx"), type: "route", pattern: "/question-lab/", routePattern: "/question-lab" },
  { id: "/store/index", mod: () => import("../routes/store/index.tsx"), type: "route", pattern: "/store/", routePattern: "/store" },
];
